# Generated by Django 2.2.3 on 2019-10-05 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('E', 'Erkək'), ('D', 'Dişi')], max_length=55, null=True)),
                ('breed', models.CharField(blank=True, choices=[('Y/Ətlik-südlük', 'Yerli : Ətlik-Südlük -- Ağqulaq'), ('Y/Ətlik-südlük', 'Yerli : Ətlik-Südlük -- Qafqaz qonuru'), ('X/Ətlik-südlük', 'Xarici : Ətlik-Südlük -- Simmental'), ('X/Südlük', 'Xarici : Südlük -- Holstein Friesian'), ('X/Südlük', 'Xarici : Südlük -- Brown Swiss'), ('X/Südlük', 'Xarici : Südlük -- Jersey'), ('X/Südlük', 'Xarici : Südlük -- Hereford'), ('X/Ətlik', 'Xarici : Ətlik -- Angus'), ('X/Ətlik', 'Xarici : Ətlik -- Limousin'), ('X/Ətlik', 'Xarici : Ətlik -- Sharole'), ('X/Ətlik', 'Xarici : Ətlik -- Texas Longhorn'), ('X/Ətlik', 'Xarici : Ətlik -- Shorthorn'), ('X/Ətlik', 'Xarici : Ətlik -- Belgian Blue')], max_length=55, null=True)),
                ('feed', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Saman', ' Saman'), ('Senaj', 'Senaj'), ('Quru ot', 'Quru ot'), ('Ot unu', 'Ot unu'), ('Çiyid qabigi', 'Çiyid qabigi'), ('Taxil', 'Taxil bitkileri'), ('Paxlalı', 'Paxlalı bitkiler'), ('Emal qalıqları', 'Emal qalıqlarıaman'), ('Kök yumruları', 'SaKök Kök yumruları'), ('Şəkər çuğunduru', 'Şəkər çuğunduru'), ('Yaşıl kütlə', 'Yaşıl kütlə'), ('Bostan bitkiləri', 'Bostan bitkiləri'), ('Silos', 'Silos'), ('Ət unu', 'Ət unu'), ('Sümük unu', 'Sümük unu'), ('Ət-sümük unu', ' Ət-sümük unu'), ('Balıq unu', ' SaBalıq unuman'), ('Üzlü süd əvəzediciləri', ' Üzlü süd əvəzediciləri')], max_length=55, null=True)),
                ('special_case', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('publish_date', models.DateField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
