# Generated by Django 2.2.3 on 2019-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cows/'),
        ),
    ]
