# Generated by Django 2.2.3 on 2019-10-06 07:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0002_auto_20191006_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='breed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Y/Ətlik-südlük', 'Yerli : Ətlik-Südlük -- Ağqulaq'), ('Y/Ətlik-südlük', 'Yerli : Ətlik-Südlük -- Qafqaz qonuru'), ('X/Ətlik-südlük', 'Xarici : Ətlik-Südlük -- Simmental'), ('X/Südlük', 'Xarici : Südlük -- Holstein Friesian'), ('X/Südlük', 'Xarici : Südlük -- Brown Swiss'), ('X/Südlük', 'Xarici : Südlük -- Jersey'), ('X/Südlük', 'Xarici : Südlük -- Hereford'), ('X/Ətlik', 'Xarici : Ətlik -- Angus'), ('X/Ətlik', 'Xarici : Ətlik -- Limousin'), ('X/Ətlik', 'Xarici : Ətlik -- Sharole'), ('X/Ətlik', 'Xarici : Ətlik -- Texas Longhorn'), ('X/Ətlik', 'Xarici : Ətlik -- Shorthorn'), ('X/Ətlik', 'Xarici : Ətlik -- Belgian Blue')], max_length=55, null=True),
        ),
    ]
