# Generated by Django 2.2.3 on 2019-10-06 09:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0003_auto_20191006_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofields',
            name='image',
        ),
        migrations.AlterField(
            model_name='infofields',
            name='feed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Saman', ' Saman'), ('Senaj', 'Senaj'), ('Quru ot', 'Quru ot'), ('Ot unu', 'Ot unu'), ('Çiyid qabigi', 'Çiyid qabigi'), ('Buğda', 'Buğda'), ('Çovdar', 'Çovdar'), ('Arpa', 'Arpa'), ('Vələmir', 'Vələmir'), ('Darı', 'Darı'), ('Düyü', 'Düyü'), ('Qarğıdalı', 'Qarğıdalı'), ('Yem noxudu', 'Yem noxudu'), ('Soya', 'Soya'), ('Günəbaxan jmıxı', 'Günəbaxan jmıxı'), ('Pambıq çiyidi', 'Pambıq çiyidi'), ('Jmıx', 'Jmıx'), ('Kök yumruları', 'Kök yumruları'), ('Şəkər çuğunduru', 'Şəkər çuğunduru'), ('Yaşıl kütlə', 'Yaşıl kütlə'), ('Yem balqabağı', 'Yem balqabağı'), ('Qarpız', 'Qarpız'), ('Silos', 'Silos'), ('Ət unu', 'Ət unu'), ('Sümük unu', 'Sümük unu'), ('Ət-sümük unu', ' Ət-sümük unu'), ('Balıq unu', ' SaBalıq unuman'), ('Üzlü süd əvəzediciləri', ' Üzlü süd əvəzediciləri')], max_length=55, null=True),
        ),
    ]
